# Arithmetic Function

In [1]:
import numpy as np
var =np.array([1,2,3,4,5,6])

print("Min : ",np.min(var))
print("Max : ",np.max(var))

Min :  1
Max :  6


In [2]:
var =np.array([1,2,3,4,5,6])

print("Min : ",np.min(var),np.argmin(var))
print("Max : ",np.max(var),np.argmax(var))

Min :  1 0
Max :  6 5


In [5]:
var =np.array([[1,2,9,4],[3,4,5,6]])

print("Min : ",np.min(var,axis=0))


Min :  [1 2 5 4]


In [6]:
var=np.array([1,2,3,4])

print(np.sin(var))
print(np.cos(var))
print(np.tan(var))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128]


In [7]:
var=np.array([1,2,3,4])

print(np.sin(var))
print(np.cos(var))
print(np.tan(var))
print(np.cumsum(var))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128]
[ 1  3  6 10]
