In [1]:
import numpy as np
var1 =np.array([1,2,3,4,5])
var2 =np.array([4,5,6,7,8])

print(var1+var2)

[ 5  7  9 11 13]


In [6]:
var1=np.array([1,2,3,4,5])
print(var1.shape)
print()
print(var1)

var2=np.array([5,6,7,8,9])
print(var2.shape)
print()
print(var2)

(5,)

[1 2 3 4 5]
(5,)

[5 6 7 8 9]


In [7]:
var1=np.array([1,2,3,4,5])
print(var1.shape)
print()
print(var1)

var2=np.array([5,6,7,8,9])
print(var2.shape)
print()
print(var2)

print(var1+var2)

(5,)

[1 2 3 4 5]
(5,)

[5 6 7 8 9]
[ 6  8 10 12 14]
