# zero()

In [1]:
import numpy as np
a_zero=np.zeros(6)
a_zero1=np.zeros((4,5))

print(a_zero)
print()
print(a_zero1)

[0. 0. 0. 0. 0. 0.]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


# One()

In [3]:
a_one=np.ones(7)

print(a_one)

[1. 1. 1. 1. 1. 1. 1.]


# range()

In [4]:
a_rm=np.arange(9)

print(a_rm)

[0 1 2 3 4 5 6 7 8]


# diagonal()

In [5]:
a_dig=np.eye(6)

print(a_dig)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


# linespace()

In [9]:
a_lin=np.linspace(0,50,num=10)

print(a_lin)

[ 0.          5.55555556 11.11111111 16.66666667 22.22222222 27.77777778
 33.33333333 38.88888889 44.44444444 50.        ]
