In [2]:
import numpy as np
var=np.array([1,2,3,4,5,6,7])

for i in var:
    print(i)

1
2
3
4
5
6
7


In [9]:
var1=np.array([[1,2,3,4],[6,7,8,9]])
print(var1)
print()

for i in var1:
    print(i)
    
print()
print(var1.ndim)

for j in var1:
    for k in j:
        print(k)

[[1 2 3 4]
 [6 7 8 9]]

[1 2 3 4]
[6 7 8 9]

2
1
2
3
4
6
7
8
9


In [7]:
var2=np.array([[[1,2,3,4],[9,8,7,6]]])
print(var2)
print(var2.ndim)
print()

for i in var2:
    for j in i:
        for k in j:
            print(k)

[[[1 2 3 4]
  [9 8 7 6]]]
3

1
2
3
4
9
8
7
6


In [12]:
var3=np.array([[[9,8,7,6],[6,5,4,3]]])
print(var3)
print(var3.ndim)
print()

for i in np.ndenumerate(var3):
    print(i)

[[[9 8 7 6]
  [6 5 4 3]]]
3

((0, 0, 0), 9)
((0, 0, 1), 8)
((0, 0, 2), 7)
((0, 0, 3), 6)
((0, 1, 0), 6)
((0, 1, 1), 5)
((0, 1, 2), 4)
((0, 1, 3), 3)


In [13]:
var3=np.array([[[9,8,7,6],[6,5,4,3]]])
print(var3)
print(var3.ndim)
print()

for i in np.nditer(var3):
    print(i)

[[[9 8 7 6]
  [6 5 4 3]]]
3

9
8
7
6
6
5
4
3
