In [1]:
import numpy as np
var=np.array([[1,2],[3,4]])
var1=np.array([[5,6],[7,8]])

new=np.concatenate((var,var1),axis=0)
print(var)
print()
print(var1)
print()
print(new)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [2]:
var=np.array([[1,2],[3,4]])
var1=np.array([[5,6],[7,8]])

new=np.concatenate((var,var1),axis=1)
print(var)
print()
print(var1)
print()
print(new)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]


In [4]:
var3=np.array([1,2,3,4,5])
var4=np.array([1,2,3,4,5])
new_1=np.stack((var3,var4),axis=0)
print(new_1)

[[1 2 3 4 5]
 [1 2 3 4 5]]


In [5]:
var3=np.array([1,2,3,4,5])
var4=np.array([1,2,3,4,5])
new_1=np.stack((var3,var4),axis=1)
print(new_1)

[[1 1]
 [2 2]
 [3 3]
 [4 4]
 [5 5]]


In [7]:
var3=np.array([1,2,3,4,5])
var4=np.array([1,2,3,4,5])

new_1=np.stack((var3,var4),axis=1)
new_2=np.hstack((var3,var4))
new_3=np.vstack((var3,var4))
new_4=np.dstack((var3,var4))

print(new_1)
print()
print(new_2)
print()
print(new_3)
print()
print(new_4)

[[1 1]
 [2 2]
 [3 3]
 [4 4]
 [5 5]]

[1 2 3 4 5 1 2 3 4 5]

[[1 2 3 4 5]
 [1 2 3 4 5]]

[[[1 1]
  [2 2]
  [3 3]
  [4 4]
  [5 5]]]
