In [2]:
import numpy as np
a=[1,2,3,4,5]
b=np.array(a)
print(b)

[1 2 3 4 5]


In [16]:
l=[]
for i in range(1,10):
   int_l=int(input("Enter your number : "))
   l.append(int_l)

print(np.array(l))

Enter your number : 7
Enter your number : 7
Enter your number : 8
Enter your number : 8
Enter your number : 8
Enter your number : 8
Enter your number : 8
Enter your number : 9
Enter your number : 9
[7 7 8 8 8 8 8 9 9]


In [19]:
ar2=np.array([[1,2,3,4,5],[1,2,3,7,8]])
print(ar)
print(ar.ndim)

[[1 2 3 4 5]
 [1 2 3 7 8]]
2


In [21]:
a3=np.array([[[1,2,3,4,5],[3,4,5,8,1],[1,8,5,43,3]]])
print(a3)
print(a3.ndim)

[[[ 1  2  3  4  5]
  [ 3  4  5  8  1]
  [ 1  8  5 43  3]]]
3


In [1]:
l=[]
for i in range(1,10):
   int_l=int(input("Enter your number : "))
   l.append(int_l)
a=np.array(l)
print(a)

Enter your number : 3
Enter your number : 5
Enter your number : 6
Enter your number : 4
Enter your number : 5
Enter your number : 6
Enter your number : 6
Enter your number : 6
Enter your number : 6


NameError: name 'np' is not defined