## Array

In [ ]:
import numpy as np
a=([1,2,3,4,5])
print(a)

In [3]:
a1=np.array([1,2,3,4,5])
print(a1)
print(a1.ndim)

[1 2 3 4 5]
1


In [4]:
a2=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(a2)
print(a2.ndim)

[[1 2 3 4 5]
 [1 2 3 4 5]]
2


In [10]:
a3=np.array([[[1,2,3,4,5],[1,2,3,4,5],[9,8,7,65,4]]])
print(a3)
print(a3.ndim)

[[[ 1  2  3  4  5]
  [ 1  2  3  4  5]
  [ 9  8  7 65  4]]]
3
