# rand()

In [4]:
import numpy as np
var=np.random.rand(5)

print(var)

[7.96360716e-01 4.05702607e-02 6.95783480e-01 2.09608107e-01
 7.76424618e-04]


In [5]:
var1=np.random.rand(3,6)

print(var1)

[[0.16792666 0.08291683 0.1009234  0.24243476 0.18632114 0.07658786]
 [0.29904145 0.29293524 0.65515597 0.32190329 0.65368243 0.00878903]
 [0.22398928 0.52030968 0.70941916 0.2397521  0.83579213 0.76576792]]


# randn()

In [6]:
var2=np.random.randn(6)

print(var2)

[-0.43254825 -0.53035052 -1.13145515  0.23337422 -1.71866069 -0.05033576]


# ranf()

In [7]:
var3=np.random.ranf(5)

print(var3)

[0.83435896 0.81821458 0.38689868 0.10924672 0.96820575]


# randint()

In [8]:
var4=np.random.randint(5,20,5)

print(var4)

[13  8  7 14  8]
