# shape & Reshape

In [2]:
import numpy as np
var=np.array([[1,2,3,4,5],[6,7,8,9,5]])

print(var)
print()
print(var.shape)

[[1 2 3 4 5]
 [6 7 8 9 5]]

(2, 5)


In [3]:
var=np.array([1,2,3,4,5],ndmin=4)

print(var)
print(var.ndim)
print()
print(var.shape)

[[[[1 2 3 4 5]]]]
4

(1, 1, 1, 5)


In [5]:
var =np.array([1,2,3,4,5,6,7,8,9,10])
print(var)
print(var.ndim)
print()

s=var.reshape(3,3)
print(s)
print(s.ndim)

[ 1  2  3  4  5  6  7  8  9 10]
1



ValueError: cannot reshape array of size 10 into shape (3,3)